export const storeProducts = [
    {
        id: 1,
        title: "Vsmarty - Type-I",
        img: "images/jeans1.jpg",
        price: 899,
        company: "Vsmarty",
        info:"lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum.",
        inCart: false,
        count: 0,
        total: 0, 
    },
    {
        id: 2,
        title: "Vsmarty - Type-II",
        img: "images/jeans2.jpg",
        price: 799,
        company: "Vsmarty",
        info:"lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum.",
        inCart: false,
        count: 0,
        total: 0, 
    },
    {
        id: 3,
        title: "Vsmarty - Type-III",
        img: "images/jeans3.jpg",
        price: 599,
        company: "Vsmarty",
        info:"lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum.",
        inCart: false,
        count: 0,
        total: 0, 
    },
    {
        id: 4,
        title: "Vsmarty - Type-IV",
        img: "images/jeans4.jpg",
        price: 699,
        company: "Vsmarty",
        info:"lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum.",
        inCart: false,
        count: 0,
        total: 0, 
    },
    {
        id: 5,
        title: "Vsmarty - Type-V",
        img: "images/jeans5.jpg",
        price: 399,
        company: "Vsmarty",
        info:"lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum.",
        inCart: false,
        count: 0,
        total: 0, 
    },
    {
        id: 6,
        title: "Vsmarty- Type-VI",
        img: "images/jeans6.jpg",
        price: 499,
        company: "Vsmarty",
        info:"lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum.",
        inCart: false,
        count: 0,
        total: 0, 
    },
    {
        id: 7,
        title: "Vsmarty - Type-VII",
        img: "images/jeans7.jpg",
        price: 599,
        company: "Vsmarty",
        info:"lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum.",
        inCart: false,
        count: 0,
        total: 0, 
    },
    {
        id: 8,
        title: "Vsmarty - Type-VIII",
        img: "images/jeans8.jpg",
        price: 499,
        company: "Vsmarty",
        info:"lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum.",
        inCart: false,
        count: 0,
        total: 0, 
    },

];

export const detailProduct = 
    {
        id: 1,
        title: "Google Pixel - White",
        img: "../public/images/image1.jpg",
        price: 299,
        company: "Google",
        info:"lorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsumlorem ipsum.",
        inCart: false,
        count: 0,
        total: 0, 
    };
